name: Build TA-Lib wheels for Linux

on:
  workflow_dispatch:

env:
  TALIB_C_VER: 0.4.0
  TALIB_PY_VER: 0.4.31
  PIP_NO_VERIFY: 0
  PIP_VERBOSE: 1
  CIBW_BUILD_VERBOSITY: 3
  CIBW_BEFORE_BUILD: |
    yum install -y wget tar make gcc gcc-c++ &&
    wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz &&
    tar -xzf ta-lib-0.4.0-src.tar.gz &&
    cd ta-lib/ &&
    ./configure --prefix=/usr &&
    make &&
    make install &&
    pip install -U setuptools wheel numpy Cython
  CIBW_TEST_REQUIRES: pytest pandas polars
  CIBW_TEST_COMMAND: pytest --rootdir=/ -k "not RSI and not threading" {project}/tests
  CIBW_SKIP: "pp* cp36* *-musllinux*"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
          CIBW_ARCHS_LINUX: auto aarch64

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: wheels-linux

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz
          name: sdist
